### ISSUE TITLE
Implement interactive level access indicator bar as designed in Figma

### ISSUE THREAD

**Issue by dovalid** [AgoraSpaceDAO/agora-frontend#34]
Differences to the Figma prototype:
- It should be shown statically for levels that the user has access to, not just on hover
- At levels the user don't have access to yet (while hovering over them, or having their staking modal open), it's color should be 1 or 2 swatches lighter

**Comment by KovJonas** [comment]
I just finished my first idea/implementation of this one ([commit](https://github.com/AgoraSpaceDAO/agora-frontend/commit/bec7a01db93f9d47c096537e8e8adf005a38dafe)). I'll try to explain quickly how I achieved the hover effect.
1. Since we're already using the `useLevelAccess` hook in the `Level` component, I added an `onAccessChange` prop to it, so I can "emit" the height of the `Level` components if the user has access to them. That means, when these components mount, the `Levels` component will already know the height of the indicator.
1. I also added a similar `onHoverChange` prop, which is also a function, and it basically emits the position (bottom) of the hovered `Level` component
1. We can use these values in the `Levels` component, where we set up the height of the "darker" part of the Indicator, and also the full height of it (full height will equal to `hoverLevelPos`.
1. I made an `AccessIndicator` component too (just to keep clean the source code of the `Levels` component), which accepts two props: `hoverLevelPos`, which contains the position (bottom) of the `Level` which is in hover state - this is the full height of the indicator -, and `highestLevelPos`, which should contain the cumulated height of the `Level` components the user has access to.
1. Finally, the `AccessIndicator` will apply a gradient on the indicator line, and will apply the `primary-500` color to the first part of it (these are the levels the user has access to), and `primary-300` to the rest of the indicator (which is only visible on hover state).

I also added some comments in the code in my latest commit, so you can understand it more clearly. I'll see if I can simplify it a bit.

**Comment by dovalid** [comment]
I thought we could use Framer Motion's layout components but that would actually be hackier, this is a better approach. I still think we should handle the animation itself with Framer Motion tho so we get nice spring behavior.

Some bugs I found:
- Indicator shown for hold levels with insufficient balance
- Indicator not shown for stake levels with active access
- onMouseLeave doesn't trigger if I move the mouse out through the disabled button at the right

**Comment by dovalid** [comment]
These are fixed in the latest commit, thanks!

Current bugs:
- If I move the mouse out of the level before the indicator has finished animating, it freezes for a sec then jumps back to it's starting position. It should nicely animate back from it's current position. Cancelling animations any time is a complex problem but afaik Framer Motion is capable of handling it.
- If the mouse is not over the level when I close the staking modal, the indicator should animate back to it's starting position (now it stays where it is until I move the cursor on one of the levels again)
- When moving the mouse between two levels I don't have access to from the lower to the higher one, the indicator glitches a little. It jumps back 2-3 pixels before expanding.

Possible improvements:
- Maybe instead of using one element and separating it with a linear gradient, we should have two elements, one for the levels with access and one for the hover state. This way the access indicator wouldn't bounce back when removing hover from the higher levels, and would provide the same animation for the case when the user gains access while the hover indicator is shown.
- Maybe we should color the hover indicator primary.100 only if the user has enough funds for the actual level, and use gray.100 otherwise to further indicate the disabled state. 
- In the future we could use a pulsing effect on the hover indicator when there's an ongoing transaction to the actual level. This would also be easier if we use different elements

**Comment by KovJonas** [comment]
In my latest commit, I fixed the mentioned bugs, and I also applied most of the improvements you mentioned above. Note that I changed the "spring" transition to "just", because it has some interesting (and great) properties, like damping, mass, etc, but those were actually drawbacks in our case (e.g. the "strength" and speed of the effect got higher when the indicator got higher, so it looked really bad for example between level 2 and level 3). But, at least now we have a better, more flexible `AccessIndicator` component.

**Comment by dovalid** [comment]
Nice! One thing that we could improve is that now that there's two elements, the focus indicator always starts animating from the top, even if there're two levels above it with access, so the animation appears with a delay and too fast. It should behave like it did with one element, starting from the end of the "active access" indicator.
Also, the second bug is still there for me.

I haven't dig really into the logic yet, but I feel like we could use a more declarative approach as opposed the current more imperative one, which would both simplify things and solve the mentioned problems. I think we should have a levels object in the Level component, something like
```ts
[
  {
	status: "idle" | "access" | "focus"
    isDisabled: boolean
	element: HTMLElement
  }
]
```
in which the Level components would update their data. The AccessIndicator would calculate the heights based on this, it could use [Range.getBoundingClientRect](https://developer.mozilla.org/en-US/docs/Web/API/Range/getBoundingClientRect) (with this we could also switch back to using Chakra's dividers in the stack). For the focus indicator, if there's no focused level, the end of the range would be the last level with access. In the future, we could add "loading" to the statuses and handle it in AccessIndicator too.

This is just a scratch, but you'll get the idea. What do you think?

**Comment by KovJonas** [comment]
Good point, I changed the initial height of the lighter indicator, so it animates just fine now (and we can also use other types of transition too, becuase now it starts at the correct position 🎉). For the 2nd bug (with the modal), I cannot reproduce it, but I'll try in other browsers too, it's pretty strange.

The idea for the more declarative approach is interesting, but wouldn't that be a little bit overcomplicated? Currently, we can easily get the height of one `Level` component (with `ref.current.offsetTop` and `ref.current.offsetHeight`), and pass it up to the parent. If we do this with the `onAccessChange` method, the bar will be `primary.500` color, and if we pass up its height with the `onHoverChange`, the 2nd (lighter) bar will change its height (and we can also add the `nextLevelOk` boolean param to this, which will determine the indicator's color - primary/gray). This way we only need to use one `ref` in the `Level` component, and we can get all the necessary information about its position/height via that.

Your idea is really interesting (I haven't ever heard about the `Range.getBoundingClientRect`!), I just tried it with a small vanilla JS test project, but that way I think we'd need to add classes to the levels and dividers too, then select them using `document.querySelector(All)`, and we'd also need to handle the case when there isn't a divider (below the last item of the list), and at the end, we'd also just send the height, position, and nextLevelOk (or isDisabled) values to the parent.

**Comment by dovalid** [comment]
It occours when I don't have the cursor over any other levels either.

I think it could be simpler than the current solution. The Level component would only have to keep it's state synced with it's parents state, and the AccessIndicator could contain all the needed logic based on this object. And we could easily extend the logic to handle loading state, or so the indicator's color doesn't change back to primary.100 when hovering over an accessed level after a disabled one, or so the indicator's height stays correct through changing orientation / resizing the page.

We wouldn't need querySelector, we'd pass the refs in the object. I don't think we'd need to do anything with dividers, we'd just have to provide the first and last element to Range.getBoundingClientRect and it'd give back the height of the indicator, regardless of what's between.

I'd def try this approach, than we'll be still able to roll back if it ends up feeling more complex

**Comment by KovJonas** [comment]
Okay, eventually, I implemented the mix of the two ideas:

I started with your approach, so the `Level` component handles its state in an object, just like you described a couple of days ago, and the `Levels` components just packs the state of each `Level` into one big object, then sends the data down to the `AccessIndicator` components, and most of the logic is handled there.

I still haven't used `Range.getBoundingClientRect`, and haven't brought back the Chakra UI dividers, because we couldn't really handle the hover state of the `Level` components that way (when you move the cursor e.g. from the 1st to the 2nd level, the first level will be in hover state, then when you reach the divider, none of the levels will be in hover state (but only the divider), and when you reach the 2nd level with your cursor, the 2nd level will be in hover state, so the indicator will "jump" back and forth. The calculation of the indicator height is also simpler this way (we just need to grab the status of the `Level` (from the object which contains all data about a specific level), and call the appropriate method on it.

Let me know if you like it this way (I think it's now way better/cleaner than the 1st version!), or if I misunderstood something, and we could really do some magic with `Range.getBoundingClientRect`! ;)

**Comment by dovalid** [comment]
You're right, didn't think of that regarding the dividers, yep it should def stay this way then. I don't stick to Range.getBoundingRectClient either, the gist was the more declarative approach, so I'm happy with this solution! What we could do I think is to use a state machine for the Level state/logic, which would hugely simplify things, but since now everything works as expected I think we can merge this in if you open a PR. We'll refactor it when we'll be adding the loading state
